name: Github Page Deploy Workflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TEMPLATE_SECRETE }}
          
      - name: Configure MIME types
        run: |
          echo 'AddType application/javascript .js' >> ./build/.htaccess
          echo 'AddType application/javascript .mjs' >> ./build/.htaccess
          echo 'AddType text/jsx .jsx' >> ./build/.htaccess
          echo 'AddType application/javascript .tsx' >> ./build/.htaccess
  